import { useState } from 'react'
import { useAuth } from '../state/AuthContext'
const errorText = (error: unknown) => error instanceof Error ? error.message : '요청을 처리하지 못했습니다.'
export default function LoginScreen() {
  const auth = useAuth(); const [signup, setSignup] = useState(false); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [name, setName] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  async function submit() { setBusy(true); setMessage(''); try { if (signup) await auth.signUp(email, password, name); else await auth.emailLogin(email, password) } catch (e) { setMessage(errorText(e)) } finally { setBusy(false) } }
  return <main className="flex min-h-screen items-center justify-center bg-gray-50 px-5 py-12"><section className="w-full max-w-md rounded-xl border border-gray-200 bg-white p-8">
    <p className="text-sm font-semibold text-accent">OSSTEM</p><h1 className="mt-2 text-2xl font-semibold text-gray-950">성과·성장관리</h1><p className="mt-2 text-sm text-gray-600">초대받은 구성원만 이용할 수 있습니다.</p>
    <div className="mt-7 grid grid-cols-2 border-b border-gray-200"><button onClick={() => setSignup(false)} className={`pb-3 text-sm font-semibold ${!signup ? 'border-b-2 border-accent text-accent' : 'text-gray-500'}`}>로그인</button><button onClick={() => setSignup(true)} className={`pb-3 text-sm font-semibold ${signup ? 'border-b-2 border-accent text-accent' : 'text-gray-500'}`}>초대받은 팀원 가입</button></div>
    <div className="mt-6 space-y-4">{signup && <label className="ui-label">이름<input value={name} onChange={e => setName(e.target.value)} className="ui-field mt-1" /></label>}<label className="ui-label">회사 이메일 주소<input type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="name@osstem.com" className="ui-field mt-1" /></label><label className="ui-label">앱 전용 비밀번호<input type="password" value={password} onChange={e => setPassword(e.target.value)} onKeyDown={e => e.key === 'Enter' && void submit()} placeholder={signup ? '이 앱에서 사용할 새 비밀번호' : '가입할 때 만든 비밀번호'} className="ui-field mt-1" /><span className="mt-1.5 block text-xs font-normal leading-5 text-gray-500">회사 이메일의 비밀번호가 아닙니다. 이 앱에서만 사용할 별도 비밀번호입니다.</span></label></div>
    {message && <p className="mt-4 text-sm text-danger">{message}</p>}<button onClick={() => void submit()} disabled={busy || !email || !password || (signup && !name)} className="ui-button ui-button-primary mt-6 w-full justify-center">{busy ? '처리 중…' : signup ? '가입하기' : '로그인'}</button>
    {!signup && <button onClick={() => void auth.reset(email).then(() => setMessage('앱 전용 비밀번호 재설정 메일을 보냈습니다.')).catch(e => setMessage(errorText(e)))} disabled={!email} className="mt-3 w-full text-xs text-gray-500">앱 전용 비밀번호 재설정</button>}
    <div className="my-6 flex items-center gap-3 text-xs text-gray-400"><span className="h-px flex-1 bg-gray-200" />관리자·등록된 팀장<span className="h-px flex-1 bg-gray-200" /></div><button onClick={() => void auth.googleLogin().catch(e => setMessage(errorText(e)))} className="ui-button ui-button-secondary w-full justify-center">Google 계정으로 로그인</button>
  </section></main>
}
