import { useRef, useState } from 'react'
import type { PerformanceGrade, Task, TeamMember } from '../types'
import type { PeerReviewSummary } from '../utils/peerReview'

export default function PeerReviewDetailDrawer({ task, member, currentContribution, currentGrade, summary, onApplyContribution, onApplyGrade, onClose }: { task?: Task; member?: TeamMember; currentContribution: number; currentGrade: PerformanceGrade; summary: PeerReviewSummary; onApplyContribution: () => void; onApplyGrade: () => void; onClose: () => void }) {
  const representative = summary.peerEvidence.slice(0, 2)
  const [position, setPosition] = useState(() => ({ x: Math.max(16, window.innerWidth - 480), y: 96 }))
  const dragRef = useRef<{ x: number; y: number; left: number; top: number } | null>(null)
  function startDrag(event: React.PointerEvent<HTMLDivElement>) { dragRef.current = { x: event.clientX, y: event.clientY, left: position.x, top: position.y }; event.currentTarget.setPointerCapture(event.pointerId) }
  function moveDrag(event: React.PointerEvent<HTMLDivElement>) { if (!dragRef.current) return; setPosition({ x: Math.max(8, Math.min(window.innerWidth - 420, dragRef.current.left + event.clientX - dragRef.current.x)), y: Math.max(8, Math.min(window.innerHeight - 120, dragRef.current.top + event.clientY - dragRef.current.y)) }) }
  function endDrag() { dragRef.current = null }
  return <aside style={{ left: position.x, top: position.y }} className="fixed z-50 max-h-[calc(100vh-112px)] w-[min(420px,calc(100vw-16px))] overflow-y-auto rounded-lg border border-gray-200 bg-white p-5 shadow-lg"><div onPointerDown={startDrag} onPointerMove={moveDrag} onPointerUp={endDrag} onPointerCancel={endDrag} style={{ touchAction: 'none' }} className="flex cursor-move select-none items-start justify-between gap-3 border-b border-gray-100 pb-3"><div><h2 className="text-lg font-semibold">{member?.name} / {task?.name}</h2><p className="mt-1 text-sm text-gray-500">피어리뷰 근거 · 드래그해서 이동</p></div><button type="button" onPointerDown={(event) => event.stopPropagation()} onClick={onClose} className="ui-button ui-button-ghost ui-button-sm">닫기</button></div>
    <div className="mt-5 divide-y divide-gray-200 border-y border-gray-200 text-sm"><div className="grid grid-cols-2 gap-4 py-4"><div><p className="text-xs text-gray-500">팀장 현재 기여도</p><p className="mt-1 font-semibold">{currentContribution}%</p></div><div><p className="text-xs text-gray-500">팀장 현재 수행등급</p><p className="mt-1 font-semibold">{currentGrade}</p></div></div><div className="grid grid-cols-2 gap-4 py-4"><div><p className="text-xs text-gray-500">피어 평균 기여도</p><p className="mt-1 font-semibold">{summary.peerContribution === null ? '-' : `${summary.peerContribution}%`}</p>{summary.peerContribution !== null && <button type="button" onClick={onApplyContribution} className="ui-button ui-button-secondary ui-button-sm mt-2">추천값 적용</button>}</div><div><p className="text-xs text-gray-500">피어 수행등급</p><p className="mt-1 font-semibold">{summary.recommendedGrade ?? '-'}</p>{summary.recommendedGrade && <button type="button" onClick={onApplyGrade} className="ui-button ui-button-secondary ui-button-sm mt-2">추천값 적용</button>}</div></div><div className="grid grid-cols-2 gap-4 py-4"><div><p className="text-xs text-gray-500">자기평가 기여도</p><p className="mt-1">{summary.selfContribution === null ? '-' : `${summary.selfContribution}%`}</p></div><div><p className="text-xs text-gray-500">피어리뷰 근거</p><p className="mt-1">{summary.evidenceCount}건</p></div></div></div>
    <section className="mt-6"><h3 className="text-sm font-semibold">대표 근거</h3>{representative.length === 0 ? <p className="mt-2 text-sm text-gray-500">등록된 근거가 없습니다.</p> : representative.map((review) => <div key={review.id} className="border-b border-gray-100 py-3"><p className="text-sm font-medium">{review.reviewerName}</p><p className="mt-1 text-sm leading-6 text-gray-600">{review.evidence}</p></div>)}{summary.peerEvidence.length > 2 && <details className="mt-3"><summary className="cursor-pointer text-sm font-medium text-accent">전체 근거 보기 ({summary.peerEvidence.length}건)</summary><div className="mt-2">{summary.peerEvidence.slice(2).map((review) => <div key={review.id} className="border-b border-gray-100 py-3"><p className="text-sm font-medium">{review.reviewerName}</p><p className="mt-1 text-sm text-gray-600">{review.evidence}</p></div>)}</div></details>}</section>
  </aside>
}
